import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar">
      <body
        style={{ backgroundColor: "#f2f2", color: "#000" }}
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div>hello from layout</div>
        <button style={{ backgroundColor: "#f2f2", color: "#000" }}>
          <Link href="/product">go to product</Link>
        </button>

      
        {children}
      </body>
    </html>
  );
}
