import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { inter } from "./components/ui/fonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: " Create Next App",
    template: "%s | my store app 😂"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isActive = true;

  return (
    <html lang="ar">
      <body
        className={`
          ${geistSans.variable}
          ${geistMono.variable}
          ${inter.className}
          antialiased
          min-h-screen
          bg-[#f2f2f2]
          text-black
        `}
      >
        <div className={isActive ? "bg-slate-900 text-red-200" : "bg-white text-black"}>
          Hello from layout
        </div>
<div className=" 
 min-h-screen
  bg-gray-500 "
  >

        {children}
</div>

        <div className={isActive ? "bg-slate-900 text-red-200" : "bg-white text-black"}>
          Hello from layout
        </div>
      </body>
    </html>
  );
}

